### ISSUE TITLE
Implementaion of Moviepy/ffmpeg editing option!

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#3]
I tried videogrep it was not works on windows.
So will you implement moviepy/ffmpeg editing option like vidoegrep on next version.
Thanks.

**Comment by kelciour** [comment]
I'm not sure that I understand what you mean by "implement moviepy/ffmpeg editing option like videogrep", but if you mean to be able to concatenate clips into one long clip then I'm sorry it probably won't be happen any time soon because I'm not sure how useful this option and there may not be the next version.

As an alternative you can use `playphrase.py` script with `-v` option to export clips and after that either watch them with mpv (`mpv *.mp4`) or concatenate them manually by using ffmpeg, maybe, with the help of batch files. [to resize them to the same resolution at first and concatenate them after that](https://superuser.com/a/1136854).

The second possible option is to use [videogrep](https://github.com/antiboredom/videogrep) on Windows. It works on Windows, but you can't use it with folder, you can only use it with filenames. It may not work correctly with multiple filenames, but it works fine with single file:
    
    videogrep --input "H:\English Movies\Robin Hood (1973).mp4" --search "Robin"

**Comment by ghost** [comment]
I sent you an email!

**Comment by raj6996** [comment]
Just make like Videogrep, that how it works. No need to sorry, I am not programmer, so I need to wait for you whenever you make it possible!

> As an alternative you can use playphrase.py script with -v option to export clips and after that either watch them with mpv (mpv *.mp4) or concatenate them manually by using ffmpeg, maybe, with the help of batch files. to resize them to the same resolution at first and concatenate them after that.

I don't get it, how to use this idea? If possible make clear tutorials video on youtube! Because it help novice user(started learning python from 3 months, you know programming is not easy job)


> The second possible option is to use videogrep on Windows. It works on Windows, but you can't use it with folder, you can only use it with filenames. It may not work correctly with multiple filenames, but it works fine with single file:
> videogrep --input "H:\English Movies\Robin Hood (1973).mp4" --search "Robin"


You sure! I have tried and tired to use this, so I quit and try to found alternative , but tested works fine with you tool but no editing feature like videogrep!
https://github.com/antiboredom/videogrep/issues/60
https://github.com/antiboredom/videogrep/issues/57

By the way I used you method i.e. use file name instead of only folder. But got either no.57 issue or 60.

**Comment by kelciour** [comment]
I don't know what you mean by "this idea", but if you're talking about concatenating video files with ffmpeg, I did a quick google search and found [this](https://youtu.be/1Xf1DfvVJbs) youtube video tutorial that shows how to concatenate clips with the same resolution and maybe some [how to use ffmpeg](https://youtu.be/MPV7JXTWPWI) youtube video tutorials and ffmpeg wiki about [scaling](https://trac.ffmpeg.org/wiki/Scaling#FittingintoaRectangleStatically-sizedPlayer) can be of any help too.

**Comment by raj6996** [comment]
I played ffmpeg tools, but it not good for visual editing even I know it powerful tool. I used openshotQT or vegas for editing. Ok you told me on other issue post about subcut. I will try it later, thanks for great service.

By the way, I still confused how did you use videogrep on windows, it was still mystery for me, tried latest Ubuntu Linux same error like issue 60. Sorry for weak English.

**Comment by kelciour** [comment]
> By the way, I still confused how did you use videogrep on windows

If you get something like `TypeError: 'bool' object is not iterable` that means that you're trying to input some folder and videogrep doesn't work with folders, you need to use video filename to make it work:

    videogrep --input "H:\English Movies\Robin Hood (1973).mp4" --search "Robin"

or use a list of video filenames:

    videogrep --input "H:\Robin Hood (1973).mp4" "H:\Balto (1995).mp4" "H:\Gladiator (2000).mp4" --search "Robin"

**Comment by raj6996** [comment]
Finally videogrep works on windows, but I can't run videogrep directly but I managed it...
Here is new issue....It is not your problem. You're only one to solve this videogrep mystery for me. thanks.
https://github.com/Zulko/moviepy/issues/164
